# 

#
# [](bg:#444444 fg:#585858)\
# [](fg:#0087AF) \
#[](bg:238 fg:240)\
#[](fg:237) \
#

format = """[ ](bg:240)\
$os\
$username\
[](bg:238 fg:240)\
$hostname\
${custom.powerhome}\
${custom.root}\
$directory\
$fill\
$git_branch\
$git_status\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala
[  \\$ ](bg:#303030)\
[](fg:#303030)
"""

# Disable the blank line at the start of the prompt
add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "fg:250 bg:240"
style_root = "fg:250 bg:124"
format = '[$user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "fg:250 bg:240"
disabled = true # Disabled by default

[fill]
symbol = " "

[hostname]
ssh_only = false
style = "fg:250 bg:238"
format = '[$ssh_symbol]($style)[ $hostname ]($style)'

[directory]
style = "fg:250 bg:237"
read_only = '  '
read_only_style="fg:250 bg:124"
format = '[$path ]($style)[$read_only]($read_only_style)[](fg:237)'
home_symbol = ""
truncation_length = 3
truncation_symbol = "..."
truncate_to_repo = false

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"/" = "  "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[c]
symbol = " "
style = "bg:#444444"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#06969A"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = " "
style = "bg:#444444"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#444444"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "fg:#303030 bg:#AFD700"
format = '[](fg:#AFD700)[ $symbol $branch ]($style)'

[git_status]
style = "bg:#AFD700"
format = '[$all_status$ahead_behind ]($style)[](bg:#AFD700 fg:#303030 fg:#444444)'

[golang]
symbol = " "
style = "bg:#444444"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:#444444"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#444444"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#444444"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#444444"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#444444"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = " "
style = "bg:#444444"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#444444"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:#444444"
format = '[ $symbol ($version) ]($style)'


[custom.powerhome]
command = """ /bin/echo '' """
when = """ busybox ash -c 'case "$PWD" in "$HOME" | "$HOME/"*) exit 0 ;; *) exit 1 ;; esac'"""
format = '[$output ](fg:238 bg:31)[~ ](fg:15 bg:31)[](fg:31 bg:237)'

[custom.root]
command = """ /bin/echo '/' """
when = """ busybox ash -c 'case "$PWD" in "$HOME" | "$HOME/"*) exit 1 ;; *) exit 0 ;; esac'"""
format = '[](fg:238 bg:237)[ /](fg:250 bg:237)'